version: 0.2
env:
  variables:
   # provided by code-pipeline cf template as environment_variable [which notable takes precedence over any variable placed here]
   # S3DistBucketUsEast1: like PARAMETER_STORE value "/${EnvironmentName}/S3DistBucketUsEast1"
   S3DistBucketUsEast1: "actian-dc-vector-273201455850-dist-dev-us-east-1"

phases:
  install:
    commands:
      - npm install node-exceptions
      - npm install request
      - npm install request-promise
      - aws cloudformation package --template-file deploy-sf-inform-service.yaml --s3-bucket $S3DistBucketUsEast1 --s3-prefix vsi/codepipeline-build-artifacts --output-template-file SfInformServiceDeploymentTemplate.yaml
artifacts:
  type: zip
  files:
    - SfInformServiceDeploymentTemplate.yaml