AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: "[05Mar19] An AWS Serverless Specification template describing Vector Salesforce Inform service (vsi) function."
Parameters:
  EnvironmentName:
    Type: String
    Default: dev
  OpenIdIssuerAuthority:
    Type: String
  OpenIdAppClientId:
    Type: String
  OpenIdAppClientSecret:
    Type: String
  OpenIdAppRedirectUris:
    Type: String
    # Default: >-
    #  https://stage-console.vector-dev.actian.com/users/login/callback,
    #  https://dev-console.vector-dev.actian.com/users/login/callback,
    #  http://localhost:4200/users/login/callback
    Description: In comma delimited list form
  ProductCode:
    Description: A Product Code from the MarketPlace.    
    Type: String
  SfIdentityServiceUrl:
    Description: The Salesforce Identity Service Url.    
    Type: String
  SfIdentityServiceDataUrlPath:
    Description: The Salesforce Identity Service Data [Call] Url Path.    
    Type: String
  SfIdentityServiceRestUrlPath:
    Description: The Salesforce Identity Service Rest [Call] Url Path.
    Type: String
  SfIdentUserSsmName:
    Description: The ssm paramter name for a SfIdentUser SsmName.    
    Type: String
  SfIdentPasswordSsmName:
    Description: The ssm paramter name for a SfIdentPassword SsmName.    
    Type: String
  SfIdentSecurityTokenSsmName:
    Description: The ssm paramter name for a SfIdentSecurityToken SsmName.    
    Type: String
  VsiAdditionalEmailRecipients:  
    Description: "The email address [Note must begin with ,] for additional notification as Email Recipients like Marketing, Accounting etc. [no more than four]"
    Type: String
  VectorWatchEnvironmentStage:
    Description: "The name of the vector watch notification that is which environment stage, e.g. 'blue' or 'green'."
    Type: String
    Default: "green"
  S3DistBucket:
    Type: String
Resources:
  DcVectorSfAccessServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub '${EnvironmentName}-${AWS::Region}-DcVectorSfAccessServiceRole'
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
  FnSfidentAccessCodeSendEmail:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub '${EnvironmentName}-sfident-access-code-send-email'
      Handler: sfident-q-access-code-send-email.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Description: 'Lambda function to provide salesforce ident access code and then send email to customer'
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt DcVectorSfAccessServiceRole.Arn
      #  [Rest]Api:
      #      Method: POST
      Environment:
        Variables:
          AWS_DEPLOYMENT_REGION: !Sub '${AWS::Region}'
          OID_APP_CLIENT_ID: !Ref OpenIdAppClientId
          OID_APP_CLIENT_SECRET: !Ref OpenIdAppClientSecret
          OID_APP_REDIRECT_URIS_COMMA_DELIMITED_LIST: !Ref OpenIdAppRedirectUris
          OID_ISSUER_AUTHORITY: !Ref OpenIdIssuerAuthority
          PRODUCT_CODE: !Ref ProductCode
          SF_IDENTITY_SERVICE_URL: !Ref SfIdentityServiceUrl
          SF_IDENTITY_SERVICE_DATA_URL_PATH: !Ref SfIdentityServiceDataUrlPath
          SF_IDENTITY_SERVICE_REST_URL_PATH: !Ref SfIdentityServiceRestUrlPath
          SF_IDENT_ACCESS_USER_SSM_NAME: !Ref SfIdentUserSsmName
          SF_IDENT_ACCESS_PASSWORD_SSM_NAME: !Ref SfIdentPasswordSsmName
          SF_IDENT_ACCESS_SECURITY_TOKEN_SSM_NAME: !Ref SfIdentSecurityTokenSsmName
          VSI_ADDITIONAL_EMAIL_RECIPIENTS: !Ref VsiAdditionalEmailRecipients
          VECTOR_WATCH_ALARM_NOTIFICATION_ARN:
            Fn::ImportValue:
              !Sub '${EnvironmentName}-${VectorWatchEnvironmentStage}-cloud-vector-watch'
  FnSfidentAccessCodeUnsubscribe:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub '${EnvironmentName}-sfident-access-code-unsubscribe'
      Handler: sfident-q-access-code-unsubscribe.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Description: 'Lambda function to provide salesforce ident access code and then unsubscribe customer'
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt DcVectorSfAccessServiceRole.Arn
      #  [Rest]Api:
      #      Method: POST
      Environment:
        Variables:
          AWS_DEPLOYMENT_REGION: !Sub '${AWS::Region}'
          OID_APP_CLIENT_ID: !Ref OpenIdAppClientId
          OID_APP_CLIENT_SECRET: !Ref OpenIdAppClientSecret
          OID_APP_REDIRECT_URIS_COMMA_DELIMITED_LIST: !Ref OpenIdAppRedirectUris
          OID_ISSUER_AUTHORITY: !Ref OpenIdIssuerAuthority
          PRODUCT_CODE: !Ref ProductCode
          SF_IDENTITY_SERVICE_URL: !Ref SfIdentityServiceUrl
          SF_IDENTITY_SERVICE_DATA_URL_PATH: !Ref SfIdentityServiceDataUrlPath
          SF_IDENTITY_SERVICE_REST_URL_PATH: !Ref SfIdentityServiceRestUrlPath
          SF_IDENT_ACCESS_USER_SSM_NAME: !Ref SfIdentUserSsmName
          SF_IDENT_ACCESS_PASSWORD_SSM_NAME: !Ref SfIdentPasswordSsmName
          SF_IDENT_ACCESS_SECURITY_TOKEN_SSM_NAME: !Ref SfIdentSecurityTokenSsmName
          VECTOR_WATCH_ALARM_NOTIFICATION_ARN:
            Fn::ImportValue:
              !Sub '${EnvironmentName}-${VectorWatchEnvironmentStage}-cloud-vector-watch'
Outputs:
  LambdaExecutionRole:
    Description: Arn of Lambda execution role
    Value: !GetAtt DcVectorSfAccessServiceRole.Arn
  FnSfidentAccessCodeSendEmailLambdaName:
    Description: Name of Lambda function to provide salesforce ident access code and then send email to customer
    Value: !Ref FnSfidentAccessCodeSendEmail
  FnSfidentAccessCodeSendEmailLambdaArn:
    Description: Name of Lambda function to provide salesforce ident access code and then send email to customer
    Value: !GetAtt FnSfidentAccessCodeSendEmail.Arn
  FnSfidentAccessCodeUnsubscribeLambdaName:
    Description: ARN of Lambda function to provide salesforce ident access code and then unsubscribe customer
    Value: !Ref FnSfidentAccessCodeUnsubscribe
  FnSfidentAccessCodeUnsubscribeLambdaArn:
    Description: ARN of Lambda function to provide salesforce ident access code and then unsubscribe customer
    Value: !GetAtt FnSfidentAccessCodeUnsubscribe.Arn